### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by shenxiangzhuang** [ai-glimpse/toyml#84]
## Clustering
- [x] K-means, K-means++, Bisecting K-means
- [x] Agnes
- [x] DBSCAN

## Classification
- [x] KNN
- [ ] Perceptron
- [ ] Logistic Regression
- [ ] Decision Tree(ID3, ID4.5)
- [ ] SVM

## EM
- [ ] Gaussian mixture model(compare with K-means)
- [ ] Dawid-Skene algorithm
